base: scoreperformer/base.yaml

_general_:
  device: cuda:0
  seed: 23

  _dirname_: results
  _label_: ScorePerformer_noIOTie


data:
  dataset:
    root: ???


model:
  perf_decoder:
    lm_head:
      _target_: lm
