base: scoreperformer/base.yaml

_general_:
  device: cuda:0
  seed: 23

  _dirname_: results
  _label_: ScorePerformer_noMaskedSeq


data:
  dataset:
    root: ???


model:
  perf_decoder:
    token_embeddings:
      _target_: simple
      multiseq_mode:
        _disable_: true
